{
    __type(name:"AssetRelayID") {
        kind
        name
        description
        interfaces {
            name
        }
        possibleTypes {
            name
        }
        enumValues {
            name
        }
        inputFields {
            name
        }
        ofType {
            name
        }
        fields {
            name
        }
    }
}